<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image\1.png" />
    <None Remove="Image\2.png" />
    <None Remove="Image\background.png" />
    <None Remove="Image\backgroundSignIn.png" />
    <None Remove="Image\logo.png" />
    <None Remove="Image\profile.png" />
    <None Remove="Image\WelcomeBack.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro.IconPacks" Version="5.0.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="5.1.0" />
    <PackageReference Include="MaterialDesignColors" Version="3.1.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Image\1.png" />
    <Resource Include="Image\2.png" />
    <Resource Include="Image\background.png" />
    <Resource Include="Image\backgroundSignIn.png" />
    <Resource Include="Image\logo.png" />
    <Resource Include="Image\profile.png" />
    <Resource Include="Image\WelcomeBack.png" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\ClassroomManagement.Application\ClassroomManagement.Application.csproj" />
    <ProjectReference Include="..\src\ClassroomManagement.Infrastructure\ClassroomManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
